import type { Metadata } from "next";
import "../styles/globals.css";
import { motion } from "motion/react"

export const metadata: Metadata = {
  title: "Vocab App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
